plugins {
    id "com.android.application"
}

def levixelVersion = providers.gradleProperty("levixelVersion").getOrElse("1.0.0")

base {
    archivesName = "android-plugins-test"
}

android {
    namespace = "com.sandrox.integratedplugins.androidtest"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.sandrox.integratedplugins.androidtest"
        minSdk = 23
        targetSdk = 36
        versionCode = 1
        versionName = "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(
                    getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.activity:activity:1.11.0"
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.recyclerview:recyclerview:1.4.0"
    implementation "com.google.android.material:material:1.13.0"
    implementation "com.github.bumptech.glide:glide:4.16.0"
    implementation "io.gitee.sandrox:levixel:${levixelVersion}"
}
